### ISSUE TITLE
Issue #1 False word counter

### ISSUE THREAD

**Issue by gifhary** [STIW3054-A181/Repo_Arif#1]
countWord method in WordCounter class read more than what is really in the file. The file contains 170 words by Microsoft Word application, but the program read it 171 words.
another example, the file contain 10 words (i have counted it manually and really believe it 10 words), the program read it as 11.

It looks like the method consider "Enter" button as a word, or any other invisible characters

**Comment by arifakashah** [comment]
also if counting high chars pdf files, it given wrong output
![image](https://user-images.githubusercontent.com/38689460/49884824-bf0ea380-fe70-11e8-98ce-e382d073e19f.png)

p/s need to revise again WordCounter class

**Comment by gifhary** [comment]
this issue is fixed

`public static int countWord(String str) {
        int countWord = 0;

        if (!(str.equals(""))) {

            String[] wordList = str.split("\\s+");
            countWord += wordList.length;
        }
        return countWord;
    }`
